#pragma config(Sensor, in1,    LF,             sensorLineFollower)
#pragma config(Motor,  port3,           MotorA,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: Ball Sorter
Team Members: Zach K., Aedan C.
Date:
Section:


Task Description:Sort marbles based off of type into seperate containers (wood, steel, plastic)


Pseudocode:

*/


task main()
{                               //Program begins, insert code within curly braces
	int homePos = 10; //home position for sorter arm

	while (1==1){
		//ball assist mover code
		startMotor(MotorA,15);
		//Starts the servo at homepostion
		setServo(Servo,homePos);
		//if ball is darker than stated value it drops to separate area for wood
		if(SensorValue(LF)<1800){
			setServo(Servo,80);
			wait(1);
		}
		//resets the servo to home position for plastic sort
		setServo(Servo,homePos);
	}
}
