#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl3,  bumpSwitch,     sensorTouch)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

char bob;
bob = SensorValue(sonar);
untilBump(bumpSwitch);
	startMotor(rightMotor, 88);
	startMotor(leftMotor,  80);
	untilSonarLessThan(8, sonar);
	stopMotor(rightMotor);
	stopMotor(leftMotor);
		wait(5);
	startMotor(rightMotor,88);
	startMotor(leftMotor,-80);
    untilSonarGreaterThan(bob-2,sonar);
  stopMotor(rightMotor);
  stopMotor(leftMotor);
}
