#pragma config(Sensor, in1,    Linefl,         sensorLineFollower)
#pragma config(Sensor, in2,    Potent,         sensorPotentiometer)
#pragma config(Sensor, in3,    LightSens,      sensorReflection)
#pragma config(Sensor, dgtl1,  LimitS,         sensorTouch)
#pragma config(Sensor, dgtl2,  Butt,           sensorTouch)
#pragma config(Sensor, dgtl3,  QuadEn,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  Sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, LED,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           Flash,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           MotorR,        tmotorVex269_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           MotorL,        tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           ServoM,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title:
Team Members:
Date:
Section:


Task Description: Program the VEX Cortex so that when the limit switch is pressed, the flashlight responds to light.
When the limit switch is pressed, the flashlight should turn on when it is dark in the room
(or when the sensor is blocked) and off when it is bright in the room. When the limit switch is not pressed,
the flashlight should always be off. The program should loop indefinitely, waiting until the limit switch is pressed
again. If your group doesn?t have the flashlight, use a motor instead.


Pseudocode: when limit switch is pressed and if the room is dark then the flashlight will turn on. when the limit switch is
is not pressed then

*/

task main()
{
int motorCount;
motorCount = 0;
while (motorCount < 3)
{
    startMotor(MotorR, 95);
    wait(2);
    stopMotor(MotorR);
    wait(2);
    motorCount = motorCount + 1;
}
}
